name: Mobile Automation Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 8 * * *"  # Triggers workflow at 8 AM IST daily

jobs:
  hirebus-automation-mobile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Generate Random Delay
        run: |
          START_HOUR=8
          END_HOUR=19
          RANDOM_HOUR=$((RANDOM % (END_HOUR - START_HOUR + 1) + START_HOUR))
          RANDOM_MINUTE=$((RANDOM % 60))
          RANDOM_SECOND=$((RANDOM % 60))
          echo "Random execution time set for $RANDOM_HOUR:$RANDOM_MINUTE:$RANDOM_SECOND IST"
          
          # Calculate the waiting time in seconds
          CURRENT_TIME=$(TZ=Asia/Kolkata date +%H:%M:%S)
          TARGET_TIME=$(printf "%02d:%02d:%02d" $RANDOM_HOUR $RANDOM_MINUTE $RANDOM_SECOND)
          
          NOW_SECONDS=$(date -d "$CURRENT_TIME" +%s)
          TARGET_SECONDS=$(date -d "$TARGET_TIME" +%s)
          
          if [ "$TARGET_SECONDS" -gt "$NOW_SECONDS" ]; then
            SLEEP_TIME=$((TARGET_SECONDS - NOW_SECONDS))
          else
            SLEEP_TIME=0
          fi
          
          echo "Sleeping for $SLEEP_TIME seconds..."
          sleep $SLEEP_TIME
          echo "Executing tests now..."

      - name: Execute Mobile Automation Tests
        env:
          # To run on Kobiton, set KOBITON to a truthy value
          KOBITON: true
          # Kobiton credentials (if you want to override the defaults)
          KOBITON_USERNAME: alphabin
          KOBITON_API_KEY: 576df69c-a63c-438d-a373-4545cd729093
          # Real device settings
          REAL_DEVICE_ID: '0a7922ac7d76'
          DEVICE_NAME: 'Redmi 12'
          # Kobiton device settings
          KOBITON_REAL_DEVICE_ID: 'RFCW32AK7QR'
          SESSION_NAME: "Automation On Kobiton"
        run: npx wdio run ./wdio.conf.js --logLevel error

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/
