name: Mobile Automation Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hirebus-automation-mobile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Execute Mobile Automation Tests
        env:
          # To run on Kobiton, set KOBITON to a truthy value
          KOBITON: true
          # Kobiton credentials (if you want to override the defaults)
          KOBITON_USERNAME: alphabin
          KOBITON_API_KEY: 576df69c-a63c-438d-a373-4545cd729093
          # Real device settings
          REAL_DEVICE_ID: '0a7922ac7d76'
          DEVICE_NAME: 'Redmi 12'
          # Kobiton device settings
          KOBITON_REAL_DEVICE_ID: 'RFCW32AK7QR'
          SESSION_NAME: "Automation On Kobiton"
        run: npx wdio run ./wdio.conf.js --logLevel error

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/
